version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nest:
        patterns: ['@nestjs/*']
      tooling:
        patterns:
          ['eslint*', '@eslint/*', 'typescript-eslint', 'prettier', 'jest', 'ts-jest', '@types/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
